name: Go

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Run tests
        run: |
          make test

      - name: Build main.wasm
        run: |
          make main.wasm

      - name: Upload main.wasm
        uses: actions/upload-artifact@v4
        with:
          name: main.wasm
          path: main.wasm

  gh-pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Download main.wasm
        uses: actions/download-artifact@v4
        with:
          name: main.wasm
          path: gh-pages/src/build

      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v5

      - name: Build site
        working-directory: gh-pages
        run: |
          deno task build --dest=_site --location="${{ steps.setup-pages.outputs.base_url }}"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
