name: Go

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Run tests
        run: |
          make test

      - name: Build main.wasm
        run: |
          make main.wasm

      - name: Upload main.wasm
        uses: actions/upload-artifact@v4
        with:
          name: main.wasm
          path: main.wasm
